Update deploy-to-gke-no-dns.yml

diff --git a/.github/workflows/deploy-to-gke-no-dns.yml b/.github/workflows/deploy-to-gke-no-dns.yml
--- a/.github/workflows/deploy-to-gke-no-dns.yml
+++ b/.github/workflows/deploy-to-gke-no-dns.yml
@@ -65,14 +65,15 @@ jobs:
 
       - name: Check if all required secrets are set
         run: |
-          REQUIRED_SECRETS=("GCP_SA_KEY" "GCP_PROJECT_ID" "GKE_CLUSTER_ZONE" "GKE_CLUSTER_NAME")
-          for secret in "${REQUIRED_SECRETS[@]}"; do
-            if [[ -z "${{ secrets[$secret] }}" ]]; then
-              echo "Error: $secret is not set."
-              exit 1
-            fi
-          done
-          echo "All required secrets are set."
+            REQUIRED_SECRETS=("GCP_SA_KEY" "GCP_PROJECT_ID" "GKE_CLUSTER_ZONE" "GKE_CLUSTER_NAME")
+            for secret in "${REQUIRED_SECRETS[@]}"; do
+              if [[ -z="${{ secrets[`${secret}`] }}" ]]; then
+                echo "Error: $secret is not set."
+                exit 1
+              fi
+            done
+            echo "All required secrets are set."
+
           
       - name: Verify Service Account
         run: |
