Update deploy-to-gke-no-dns.yml

diff --git a/.github/workflows/deploy-to-gke-no-dns.yml b/.github/workflows/deploy-to-gke-no-dns.yml
--- a/.github/workflows/deploy-to-gke-no-dns.yml
+++ b/.github/workflows/deploy-to-gke-no-dns.yml
@@ -23,6 +23,15 @@ jobs:
       with:
         project_id: ${{ secrets.GCP_PROJECT_ID }}
 
+    - name: Check if GCP_SA_KEY secret is set
+      run: |
+        if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
+          echo "GCP_SA_KEY is not set or is empty"
+          exit 1
+        else
+          echo "GCP_SA_KEY is set"
+        fi
+
     - name: Validate GCP_SA_KEY
       run: |
         echo "${{ secrets.GCP_SA_KEY }}" > /home/runner/work/darkseek/darkseek/gcloud.json
@@ -49,7 +58,7 @@ jobs:
                 missing_keys.append(key)
         
         if missing_keys:
-            print(f'Error: Missing required keys in GCP_SA_KEY: {', '.join(missing_keys)}')
+            print(f'Error: Missing required keys in GCP_SA_KEY: {", ".join(missing_keys)}')
             sys.exit(1)
         
         print('GCP_SA_KEY validation successful!') # Add a success message for clarity
